"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const controller_1 = require("../controller/controller");
const registerSchema_1 = require("../dto/registerSchema");
const requestValidator_1 = require("../dto/requestValidator");
const auth_controller_1 = require("../controller/auth.controller");
const tokenValidator = new auth_controller_1.AuthValidation();
const router = express_1.default.Router();
const controller = new controller_1.ControllerClass();
router.get('/', controller.healthChecker);
router.post("/sign-up", registerSchema_1.registerSchema, requestValidator_1.requestValidation, controller.signUp);
router.post("/token", controller.getToken);
router.get("/list", tokenValidator.checkAuthorizationToken, controller.listUsers);
router.get("/list/:userId", tokenValidator.checkAuthorizationToken, controller.listUserById);
router.post("/calculate", tokenValidator.checkAuthorizationToken, controller.getCalculations);
router.post("/calculate/:est", tokenValidator.checkAuthorizationToken, controller.getCalculations);
router.post("/test-route/:testNumber", tokenValidator.checkAuthorizationToken, controller.testScript);
router.post("/estimate/:enum", tokenValidator.checkAuthorizationToken, controller.getEstimate);
router.post("/print/:enum", tokenValidator.checkAuthorizationToken, controller.generatePdf);
router.get("/report/:enum", controller.sendPdf);
exports.default = router;
